project_name: mgccli
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Gefferson Ferraz <me@gefferson.com.br>
  description: Test GO Releaser.
  homepage: https://github.com/geffersonFerraz/test-goreleaser
  license: MIT
  formats:
  - deb
  - rpm

brews:
  -
    name: mgccli
    homepage: "https://test.geff.ws/download/cli/latest"  
    repository:
      owner: geffersonFerraz
      name: homebrew-test
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: geffersonFerraz
      email: me@gefferson.com.br
    url_template: "http://test.geff.ws/download/cli/{{ .Tag }}/{{ .ArtifactName }}"

