project_name: mgccli
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Carlos A Becker <root@carlosbecker.dev>
  description: Sample project.
  homepage: https://github.com/geffersonFerraz/test-goreleaser
  license: MIT
  formats:
  - deb
  - rpm

brews:
  -
    name: mgccli
    homepage: "https://github.com/geffersonFerraz/test-goreleaser"
    tap:
      owner: geffersonFerraz
      name: homebrew-test
    commit_author:
      name: geffersonFerraz
      email: me@gefferson.com.br
