name: MGC SDK CI

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.22.0'
          cache-dependency-path: "**/go.sum"
      - run: go version
      - name: Build CLI
        env:
          VERSION: CI
          CHECK_RELEASE: 0
        run: ./scripts/build_release.sh
